---
name: Terraform CI Job
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - terraform/*.tf
      - '**.y?ml'

env:
  TERRAFORM_WORK_DIR: terraform #Subdirectory where main terraform files are stored
  python_version: 3.9

permissions:
  id-token: write
  contents: read

jobs:
  Terraform:
    name: 'Terraform CI'
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        with:
          ref: master

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.python-version }}

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2

      - name: "Setup Terragrunt"
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: latest

      - name: "Setup TFLint"
        uses: lablabs/setup-tflint@v1
        with:
          tflint_version: latest
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: "Run Pre-Commit hooks"
        uses: pre-commit/action@v3.0.0
        env:
          extra_args: --all-files --verbose
          SKIP: "terraform_tfsec,detect-aws-credentials,terraform_docs"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.SECRET_GITHUB_OIDC_ROLE_ARN }}

      - name: Check AWS Credentials
        run: aws sts get-caller-identity

      - name: Terragrunt init
        run: |
          cd ${{ env.TERRAFORM_WORK_DIR }}
          terragrunt init --terragrunt-non-interactive

      - name: "Terraform validate"
        run: |
          terraform -chdir="$TERRAFORM_WORK_DIR" validate

      - name: "Test with Checkov"
        run: |
          cd "$TERRAFORM_WORK_DIR"
          pip install checkov
          checkov -d . --skip-check "CKV_AWS_116,CKV_AWS_117,CKV_AWS_73,CKV_AWS_120,CKV2_AWS_29,CKV_AWS_158,CKV_AWS_26,CKV_AWS_115,CKV_AWS_21,CKV_AWS_18,CKV_AWS_144,CKV_GIT_2,CKV_AWS_147,CKV_AWS_173,CKV_AWS_45,CKV_AWS_107,CKV_AWS_108,CKV_AWS_111,CKV_AWS_110,CKV_AWS_109"

      - name: "Terraform apply"
        run: |
          export TF_VAR_deployment_role="${{ secrets.SECRET_GITHUB_OIDC_ROLE_ARN }}"
          export TF_VAR_github_token="${{ secrets.GH_TOKEN }}"
          terraform -chdir="$TERRAFORM_WORK_DIR" apply -auto-approve
